[global]
error_log = /var/log/php-fpm/laravel.log
log_limit = 8192
[www]
user = www-data
group = www-data
listen = 0.0.0.0:9000
pm = static
pm.max_children = 1
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3
catch_workers_output = yes
slowlog = /var/log/php-fpm/slow.log
request_slowlog_timeout = 5s
access.format = "%R - %u %t \"%m %r\" %s"